apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xhmvfeekp-python 
  janus-idp.io/tekton: xhmvfeekp-python
  backstage.io/kubernetes-id: xhmvfeekp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xhmvfeekp-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml